---

- name: Install Consul
  block:
    - unarchive:
        src: "{{ consul_download_url }}"
        dest: /opt/
        remote_src: yes

- name: Template out the service file for consul
  template:
    src: "{{ role_path }}/files/consul.service.j2"
    dest: "/etc/systemd/system/consul.service"
    owner: root
    group: root
    mode: 0644

- name: Start service consul
  systemd:
    name: consul
    state: restarted
    enabled: yes
    daemon_reload: yes